### PR TITLE
Inventory System, carrying mechanics and Pause menu

### PR DESCRIPTION
**Pull request by yinghj**

### CODE REVIEW

**Comment by Charlieranderson** [comment]
Looks good.

**Comment by Charlieranderson** [comment]
Also just wanted to say thanks for editing the comments to be more specific and clear. That is a big help.

**Comment by adanter** [comment]
I'm not 100% sure if I'm reading this correctly, but it looks like you committed a bunch of files specific to your Unity scene which we don't actually want in our Prairie repo.  For example, this one doesn't look like built-in Prairie code, unless this is part of some built-in test scene or something that I didn't know about:

Project/Assets/Prairie/Prototype/Audio/20 (Sittin' On) The Dock Of The Bay.mp3.meta

**Comment by yinghj** [comment]
Good point, Adante. @Charlieranderson can you take a look at your commits and see which prefabs and metas are actually the changes you made vs Unity changes, and reset those unintended changes? Thank you!

**Comment by yinghj** [comment]
Need to reorganize commits in this pull request.

**Pull request closed without merging**
