### PR TITLE
TwineNode to Scene Interactions

### PR DESCRIPTION
**Pull request by SeaC0w**
Added other interaction (rotation, translation, enable) functionality to TwineNode, no conflicts expected.
Currently one node can only rotate/transforms its associated objects all the same amount, as giving each associated objects its own rotate/transform matrix would make things waaay too cluttered.

### CODE REVIEW

**Comment by yinghj** [comment]
Is this pl suppose to be reviewed, or is it still in progress? @SeaC0w

**Comment by SeaC0w** [comment]
This is supposed to be reviewed and merged, its fully working with no expected conflicts with the rest of the TwineNode changes.

**Comment by yinghj** [comment]
Do we want the gressenhall asset in master or just in our final presentation branch?

**Comment by yinghj** [comment]
Also please resolve the merge conflicts here.

**Comment by adanter** [comment]
I think we want to leave the gressenhall files in another branch.  No reason to have them in master, where we'll have to deal with them every time we push and pull for development purposes.

**Pull request closed without merging**
