### PR TITLE
Added keybinds, removed toggle animator and its editor, changed carry inherit

### PR DESCRIPTION
**Pull request by Charlieranderson**
Probably works... jk its fine please merge

### CODE REVIEW

**Review by tedward111 — APPROVED** [review]
LGTM!

**Review by yinghj — CHANGES_REQUESTED** [review]
Please test on different resolution. The text box for keybinding has scaling issue.

**Comment by Charlieranderson** [comment]
What resolution? I tried it on multiple and it was fine

**Comment by yinghj** [comment]
I was testing using build and run with 1440 x 900 one. The width of the text runs wider than the blue frame.

**Comment by Charlieranderson** [comment]
Word, was just testing again the problem with with wide ratios.. hm.. do i need a script to scale the text box?

**Comment by yinghj** [comment]
I attempted to make it scale by adding a layout group. It works on both the highest and lowest resolution on my mac. But we should probably test it on the bigger screen in cmc before we merge.

**Comment by Charlieranderson** [comment]
lol nice ya im testing a vertical layout group rn

**Comment by Charlieranderson** [comment]
Ill test this some more and push after we test it on the big screen, thank chelsea!

**Comment by yinghj** [comment]
Oh I already pushed the commit of adding the vertical layout into this PL (see the last commit above) but I can also revert it if yours works too!

**Comment by yinghj** [comment]
My commit is reverted now. You can push your changes.

**Comment by Charlieranderson** [comment]
thanks

**Comment by Charlieranderson** [comment]
Okay i believe this commit worked but I also accidentally pulled your commit, but i reset it, but i don't really know if i made some mistake and I have like, both our changes or something. I reset the commit to my previous one but lemme know if something is weird

**Comment by yinghj** [comment]
I think your commit is fine, since this PL doesn't have my commit rn. 

But the white space problem should be able to be fixed by adding Layout Element component to each child of your vertical layout group. I can try to see if I can fix that, or do you want to try that our yourself?

**Comment by Charlieranderson** [comment]
dang chelsea have a little trust

**Comment by Charlieranderson** [comment]
Anyways tbh I think its fine for right now, works for 3200x1800, 1920x1080, 1200x800, etc, common ratios. I don't even think all of our other GUI things adapt perfectly to every resolution out there.

**Comment by yinghj** [comment]
sorry accidentally press the wrong button.

**Comment by yinghj** [comment]
Sorry I didn't mean to sound like I was trying to modify your branch rn. Just giving some suggestions based on my experience dealing with these UI elements. 

I think you do need the Layout Element component for each children under vertical layout group so that it knows what element the group is in control of. It is just how the layout group works. Otherwise it risks other unknown unity UI behavior. 

And also selecting Force Expand on width should be able to make the text fit only within the frame and Control Size on height should be able to remove the white space since the text box will be only as tall as it needed, controlled by the layout group.  Force expand and control size are actually conflicting options so it's better not to select both on the same dimension.

**Comment by Charlieranderson** [comment]
From what I understand, the vertical layout group doesn't need the layout element to work, it just applies to the immediate children of the object with the vertical layout group component. You only need the layout element if you want to make adjustments to the layout beyond the default layout, which I don't think we need. We can look into the force expand stuff more when we meet, but i just added some stuff

**Comment by yinghj** [comment]
yeah it scales better now. thanks! and let's discuss more in person later.

**Review by yinghj — APPROVED** [review]

**Pull request merged**
